# Uncomment the next line to define a global platform for your project
platform :ios, '18.0'

target 'CoffeePlaceApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoffeePlaceApp
pod 'YandexMapsMobile', '4.8.1-lite'
end
